// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	stats "github.com/Vikktttoriya/flight-tracker/internal/domain/stats"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetLatest provides a mock function with given fields: ctx
func (_m *Repository) GetLatest(ctx context.Context) (*stats.Stats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *stats.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*stats.Stats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *stats.Stats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stats.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type Repository_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetLatest(ctx interface{}) *Repository_GetLatest_Call {
	return &Repository_GetLatest_Call{Call: _e.mock.On("GetLatest", ctx)}
}

func (_c *Repository_GetLatest_Call) Run(run func(ctx context.Context)) *Repository_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetLatest_Call) Return(_a0 *stats.Stats, _a1 error) *Repository_GetLatest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetLatest_Call) RunAndReturn(run func(context.Context) (*stats.Stats, error)) *Repository_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Repository) Save(ctx context.Context, _a1 *stats.Stats) (*stats.Stats, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *stats.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *stats.Stats) (*stats.Stats, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *stats.Stats) *stats.Stats); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stats.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *stats.Stats) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *stats.Stats
func (_e *Repository_Expecter) Save(ctx interface{}, _a1 interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, _a1 *stats.Stats)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*stats.Stats))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 *stats.Stats, _a1 error) *Repository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(context.Context, *stats.Stats) (*stats.Stats, error)) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
